### PR TITLE
Issue #53 Enhance Undo/Redo for batch operations

### PR DESCRIPTION
**Pull request by jamessral**
This is the first implementation that I could think of to get working, but I'm sure it can be improved. I welcome the feedback :smile:

Ideally, I think there is a better way down the road that is more complex. Tracking commits/diffs and pushing/popping commits is perhaps one way.

There also appears to be another issue without these changes that causes the individual pixel being reverted to not always be correct.

### CODE REVIEW

**Comment by dfirebaugh** [comment]
Sweet!

It may be better to store each commit as a `pixel_buffer` (i.e. a list of color_t for the entire canvas) and then call `Context_from_pixel_buffer` instead of `Context_swap_pixels`

https://github.com/dfirebaugh/spritely/blob/a4812bae98960323d42be2aa0ad463222b5d18cb/src/context.c#L180-L183

That way it would store/restore the entire state of the canvas.

Thanks for your work.

**Comment by jamessral** [comment]
It's my pleasure. Would you like me to add that to this PR? All I ask is that when we're done with this PR (not necessarily right now), you'd add the hacktoberfest accepted label :smile:

I'd love to keep working on this, though. I'm having a great time

**Comment by dfirebaugh** [comment]
Sure, go ahead and add it to this PR.

The project has the hacktoberfest topic.  So your PRs should count toward hacktoberfest automatically.

You're welcome to continue contributing.  There seems to be plenty to do.  We are turning this thing into a game engine!

**Comment by jamessral** [comment]
For sure. It shows up in hacktoberfest, but they changed it so that the accepted label be applied to PRs to cut down on spam. I'm excited to keep contributing. Making a game engine sounds super awesome!

**Comment by jamessral** [comment]
I'm having a bit of difficulty achieving this so far. I'm running into issues with the global contexts and their types, especially the `typedef struct Context *Context_t` bit. It's making it a bit difficult to dereference the current context's pixels.

**Comment by dfirebaugh** [comment]
@jamessral That's intentional.  The ` typedef struct Context *Context_t ` is the defninition of an [Abstract Data Type](http://pages.cs.wisc.edu/~hasti/cs367-1/readings/Introduction/index.html)

It's basically a way to have encapsulation (kind of like a class).

- The interface (i.e. what operations we can do on a `Context_t`) is defined in the header file
- The lower level stuff (i.e. how we do those things)  is defined in the .c file

This way we can change the lower level stuff (to optimize for example) without having much effect on other parts of the codebase since the interface shouldn't change drastically.

So, to access any information of a `Context_t`, you will need to make a function and expose it in `context.h`.  The function will have to take `Context_t` as an argument so it know which Context to reference

Take a look at the `Context_get_pixel` function
https://github.com/dfirebaugh/spritely/blob/27f253604260c346f5b05e5d2b15ff0be7ed7f44/src/context.c#L195-L198

We can call that function anywhere, pass in a `Context_t` object and get the pixel color (i.e. the `color_t`) at a specified index.
https://github.com/dfirebaugh/spritely/blob/81dcb871d8a666d4295afbf60fac3ed3c24a67ac/src/draw_tools.c#L33

Let me know if I can explain anything better.

**Comment by jamessral** [comment]
I've started to move it to using a pixel buffer, but it's not working consistently. Do you have any ideas here? Sorry, I'm new to this kind of thing (since I normally do web dev stuff).

**Comment by dfirebaugh** [comment]
Hey, sorry, just now seeing this.

No worries!

I went ahead and made a few changes.

I modified the fill tool a bit to make it easier.
Ideally, there should be no difference between an undo operation of a pen tool and an undo operation of a fill.


There was a weird issue with the mouse events.  I made these more momentary for now, but we will have to split out momentary mouse events from the non-momentary.  For example, the drag operation is not a momentary event, but the fill operation is a momentary event.  The way it was before, the fill operation could potentially add a bunch of commits to the undo stack.  That could be opened up as a separate issue though.

This looks like it’s working well though.
Nice work.


On a side note, I’d like to package this up as an npm module.  Ideally, you would be able to npm install spritely and then use it as a library to make games.
I did a cheap demo of this here: https://dfirebaugh.github.io/spritely/examples/pong.html
code: https://github.com/dfirebaugh/spritely/blob/master/web/examples/pong.js

There are some problems with packaging this up as a module.  Still a good ways to go before it’s fully operational as an npm package.

**Pull request merged**
