### PR TITLE
Added undo and redo functionality

### PR DESCRIPTION
**Pull request by ptrstr**
This uses a new type, `Commit`, that is a doubly linked list to other commits. This fixes issue #4

### CODE REVIEW

**Comment by Costava** [comment]
The added keyboard shortcuts should be added to the help text in `src/input.c`.

Personally, I would also want `Ctrl+Shift+Z` to redo.
`Ctrl+Y` for redo is awkward, but I do see it used in programs.

**Comment by ptrstr** [comment]
So I should add both keybinds?

**Comment by dfirebaugh** [comment]
Yes, I agree.

Both keybindings would be good.
Thanks

**Comment by dfirebaugh** [comment]
Hey, @ptrstr we've added a few things.  Could you take a look and resolve some of these conflicts?


Then we can get this merged in.

thanks,
DF

**Comment by dfirebaugh** [comment]
resolves #18

**Pull request merged**
