### PR TITLE
Fix 'multiple definition' linker errors

### PR DESCRIPTION
**Pull request by Costava**
When linking, both `main.o` and `spritely.o` had definitions for `mouse`, `window`, `renderer`, etc. which caused building to fail.
e.g.
```
/usr/bin/ld: spritely.o:/home/user/Desktop/spritely/src/globals.h:17: multiple definition of 'window'; main.o:/home/user/Desktop/spritely/src/globals.h:17: first defined here
```

Fix by using `extern` keyword in `globals.h` and have the single definition come from `globals.c`

### CODE REVIEW

**Comment by Costava** [comment]
There is a dependency on issue #10 

If these changes go into the repo, what license would they be under?

**Comment by dfirebaugh** [comment]
I added MIT license.  Is that ok with you?  If so, I'll go ahead and merge.

**Comment by Satharus** [comment]
@dfirebaugh  If you're going to merge this then make sure to remove "-z muldefs" from LDFLAGS in the makefile, as I added it as a work around for this problem to get it to compile on my system.

**Comment by Costava** [comment]
> I added MIT license. Is that ok with you? If so, I'll go ahead and merge.

All good :+1: Thanks

**Pull request merged**
