### PR TITLE
Added CMake Build System

### PR DESCRIPTION
**Pull request by alboainin**
- Cmake build system added
- gives clean directory
- easy to use
- binaries and executable can be found in "spritely/bin"

### CODE REVIEW

**Comment by AliAlboainin96** [comment]
To build run "./build.sh" 
To Clean run "./clean.sh"

**Comment by cxong** [comment]
Any thoughts on this? This would make it easier for windows/macos devs to contribute. What about only adding the `CMakeLists.txt`, and keeping the current makefile?

**Comment by AliAlboainin96** [comment]
CMake is same as make but it automate the process, for exmaple the "target_link_libraries" just pass the linker flags such as the SDL one, -lm

**Comment by AliAlboainin96** [comment]
and i tried to implem both of them and they work but i feel it defeats the point of 'cmake' bc 'make' is more messy

**Comment by dfirebaugh** [comment]
I'm a little conflicted about this.

1. the makefile seems simple enough
2. we have the wasm build.  Does this handle building to wasm?

sidenote: we also have a github action set up now that automatically deploys to [gh-pages](dfirebaugh.github.io/spritely/)
https://github.com/dfirebaugh/spritely/blob/master/.github/workflows/build-and-deploy.yml


I do appreciate that this would help people build on windows and mac though.

**Comment by AliAlboainin96** [comment]
Well its true that makefile is more simpler to setup but incase the project expand it might be a little complicated including all of these libraries, headers and essential building flags.

But i think you should give CMake a try to see

and about wasm i will try to add it today

**Comment by dfirebaugh** [comment]
Thank you for your work on this.  CMAKE was probably the right call.  Sorry for being stubborn.

I'm refactoring this project to incorporate zig.

**Pull request closed without merging**
